apiVersion: v2
name: lemonade-stand-app
description: Red Hat Pizza Assistant for ordering pizza and checking the menu
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: sarabanderby
  - name: ckavili
